from datetime import datetime
import json
import logging

from .command import (ANSI_LIGHT_GREEN, echo)
from .const import PKG_NAME
from .export import NotebookExporter
from .fileops import write_file

logger = logging.getLogger()


class NotebookExploder(object):
  """
  Explodes a list of notebooks by creating a directory and exporting
  notebooks to the specified formats (python, rst, and binary files)

  It expects all paths of notebooks and directories to be relative
  to either the root of a git repo, or some subdirectory therein.
  """

  README_MESSAGE = (
    'The files in {output_dir}/ were automatically generated by '
    '{program}. Do not edit manually.\n')
  RUNTIME_DATA_FILENAME = '.nbexplode_runtime_data.json'

  def __init__(self, output_dir, nbformat_version):
    self.start_time = datetime.now()
    self.output_dir = output_dir
    self.notebooks_exploded = 0
    # delegate exporting documents to nbconvert
    self.exporter = NotebookExporter(output_dir, nbformat_version)

  def setup(self):
    """
    Bootstraps the output directory with necessary files.
    """
    self._write_readme()
    self._write_gitignore()

  def explode(self, filepaths):
    """
    Loads and exports notebook to a predetermined set of formats.
    """
    for filepath in filepaths:
      self.exporter.load(filepath)
      self.exporter.export_python()
      self.exporter.export_rst()
      self.notebooks_exploded += 1

  def teardown(self):
    """
    Displays to the user that the program has finished executing,
    and write data about its execution to the output directory.
    """
    self._write_runtime_data(datetime.now())
    msg = "generated content for {} ipynb file(s) in {}/".format(
      self.notebooks_exploded, self.output_dir)
    echo("finished", ANSI_LIGHT_GREEN, msg)

  def _write_readme(self):
    content = self.README_MESSAGE.format(
      output_dir=self.output_dir,
      program=PKG_NAME)
    write_file(self.output_dir, 'readme.txt', content)

  def _write_gitignore(self):
    content = "\n".join(["*.log", self.RUNTIME_DATA_FILENAME])
    write_file(self.output_dir, '.gitignore', content)

  def _write_runtime_data(self, end_time):
    data = dict(
      program=PKG_NAME,
      output_dir=self.output_dir,
      time_started=str(self.start_time),
      time_finished=str(end_time),
      runtime_seconds=(end_time - self.start_time).total_seconds(),
      notebooks_exploded=self.notebooks_exploded)
    content = json.dumps(data, indent=2, sort_keys=True)
    write_file(self.output_dir, self.RUNTIME_DATA_FILENAME, content)
